stages:
  prepare_data:
    foreach: ${models}
    do:
      cmd: python src/prepare.py --preprocessor=${item.preprocessor}
      deps:
        - data/raw/train.csv
        - src/prepare.py
      outs:
        - data/prepared/${item.preprocessor}/texts.json
        - data/prepared/${item.preprocessor}/labels.json
        - data/prepared/${item.preprocessor}/preproc.joblib

  train:
    foreach: ${models}
    do:
      cmd: python src/train.py --model-name="${item.name}" --preprocessor=${item.preprocessor}
      deps:
        - data/prepared/${item.preprocessor}/texts.json
        - data/prepared/${item.preprocessor}/labels.json
        - data/prepared/${item.preprocessor}/preproc.joblib
        - src/train.py
      outs:
        - models/${item.name}.joblib
      metrics:
        - models/${item.name}_train_metrics.json:
            cache: false

  test:
    foreach: ${models}
    do:
      cmd: python src/test.py --model-name="${item.name}"  --preprocessor=${item.preprocessor}
      deps:
        - models/${item.name}.joblib
        - src/test.py
      metrics:
        - models/${item.name}_test_metrics.json:
            cache: false

  predict:
    foreach: ${models}
    do:
      cmd: python src/predict.py
      deps:
        - data/raw/test.csv
        - models/${item.name}.joblib
        - models/${item.name}_test_metrics.json
        - src/predict.py
      outs:
        - data/predictions/${item.name}_prediction.csv
