stages:
  prepare_data:
    cmd: python src/prepare.py
    deps:
      - data/raw/train.csv
      - src/prepare.py
    outs:
      - data/prepared/texts.json
      - data/prepared/labels.json
      - data/prepared/tokenizer.joblib

  train:
    foreach: ${models}
    do:
      cmd: python src/train.py --model-name=${item}
      deps:
        - data/prepared/texts.json
        - data/prepared/labels.json
        - data/prepared/tokenizer.joblib
        - src/train.py
      outs:
        - models/${item}.joblib
      metrics:
        - models/${item}_train_metrics.json:
            cache: false

  test:
    foreach: ${models}
    do:
      cmd: python src/test.py
      deps:
        - models/${item}.joblib
        - src/test.py
      metrics:
        - models/${item}_test_metrics.json:
            cache: false

  predict:
    foreach: ${models}
    do:
      cmd: python src/predict.py
      deps:
        - data/raw/test.csv
        - models/${item}.joblib
        - models/${item}_test_metrics.json
        - src/predict.py
      outs:
        - data/predictions/${item}_prediction.csv
