stages:
  fetch_data:
    cmd: ./src/fetch_data.sh && ./src/fetch_glove.sh
    deps:
      - src/fetch_data.sh
      - src/fetch_glove.sh
    outs:
      - data/raw
      - ext/
  prepare_data:
    foreach:
      - SKCountVectorizer
      - TFTokenizer
      - SKTfidfVectorizer
      - GloVeVectorizer
    do:
      cmd: python src/prepare.py --preprocessor=${item}
      deps:
        - data/raw/train.csv
        - src/prepare.py
        - src/preprocessors/abstract.py
        - src/preprocessors/${item}.py
      outs:
        - data/prepared/${item}/texts.json
        - data/prepared/${item}/labels.json
        - data/prepared/${item}/preproc.joblib
  train:
    foreach:
      - preprocessor: SKCountVectorizer
        model_class: SKLogisticRegression
        output: model.joblib
      - preprocessor: TFTokenizer
        model_class: TFConv1D
        output: model.h5
      - preprocessor: GloVeVectorizer
        model_class: TFlstm
        output: model.h5
      - preprocessor: SKTfidfVectorizer
        model_class: TFDense
        output: model.h5
    do:
      cmd: python src/train.py --model-class=${item.model_class} --preprocessor=${item.preprocessor}
      deps:
        - data/prepared/${item.preprocessor}/texts.json
        - data/prepared/${item.preprocessor}/labels.json
        - data/prepared/${item.preprocessor}/preproc.joblib
        - src/train.py
        - src/dataset.py
        - src/models/abstract.py
        - src/models/${item.model_class}.py
      params:
        - ${item.model_class}
      outs:
        - models/${item.model_class}/${item.output}
      metrics:
        - models/${item.model_class}/train_metrics.json:
            cache: false

  test:
    foreach:
      - preprocessor: SKCountVectorizer
        model_class: SKLogisticRegression
        file: model.joblib
      - preprocessor: TFTokenizer
        model_class: TFConv1D
        file: model.h5
      - preprocessor: GloVeVectorizer
        model_class: TFlstm
        file: model.h5
      - preprocessor: SKTfidfVectorizer
        model_class: TFDense
        file: model.h5
    do:
      cmd: python src/test.py --model-class=${item.model_class} --preprocessor=${item.preprocessor}
      deps:
        - models/${item.model_class}/${item.file}
        - src/test.py
      outs:
        - models/${item.model_class}/test_predictions.csv
      metrics:
        - models/${item.model_class}/test_metrics.json:
            cache: false

  predict:
    foreach:
      - preprocessor: SKCountVectorizer
        model_class: SKLogisticRegression
        file: model.joblib
      - preprocessor: TFTokenizer
        model_class: TFConv1D
        file: model.h5
      - preprocessor: GloVeVectorizer
        model_class: TFlstm
        file: model.h5
      - preprocessor: SKTfidfVectorizer
        model_class: TFDense
        file: model.h5
    do:
      cmd: python src/predict.py --model-class=${item.model_class} --preprocessor=${item.preprocessor}
      deps:
        - data/raw/test.csv
        - models/${item.model_class}/test_metrics.json
        - src/predict.py
        - models/${item.model_class}/${item.file}
      outs:
        - models/${item.model_class}/submission.csv

  compare:
    cmd: python src/compare.py
    deps:
      - src/compare.py
      - models
    outs:
      - roc_curves.png
