SKLogisticRegression:
  max_iter: 100

TFConv1D:
  lr: 0.0001
  batch_size: 512
  epochs: 200

TFDense:
  lr: 0.0001
  batch_size: 512
  epochs: 200

TFlstm:
  lr: 0.00005
  batch_size: 128
  epochs: 500
