stages:
  train:
    foreach:
      - preprocessor: SKCountVectorizer
        model_class: SKLogisticRegression
        output: model.joblib
    do:
      wdir: ../../
      cmd: python src/train.py --model-class=${item.model_class} --preprocessor=${item.preprocessor}
      deps:
        - data/prepared/${item.preprocessor}/texts.json
        - data/prepared/${item.preprocessor}/labels.json
        - data/prepared/${item.preprocessor}/preproc.joblib
        - src/train.py
      outs:
        - models/${item.model_class}/${item.output}
      metrics:
        - models/${item.model_class}/train_metrics.json:
            cache: false

  test:
    foreach:
      - preprocessor: SKCountVectorizer
        model_class: SKLogisticRegression
        file: model.joblib
    do:
      wdir: ../../
      cmd: python src/test.py --model-class=${item.model_class} --preprocessor=${item.preprocessor}
      deps:
        - models/${item.model_class}/${item.file}
        - src/test.py
      metrics:
        - models/${item.model_class}/test_metrics.json:
            cache: false

  predict:
    foreach:
      - model_class: SKLogisticRegression
        file: model.joblib
    do:
      wdir: ../../
      cmd: python src/predict.py --model-class=${item.model_class}
      deps:
        - data/raw/test.csv
        - models/${item.model_class}/test_metrics.json
        - src/predict.py
        - models/${item.model_class}/${item.file}
      outs:
        - data/predictions/${item.model_class}_prediction.csv
