vars:
  - preprocessor: TFTokenizer
  - model_class: TFConv1D
  - file: model.h5

stages:
  train:
      wdir: ../../
      cmd: python src/train.py --model-class=${model_class} --preprocessor=${preprocessor}
      deps:
        - data/prepared/${preprocessor}/texts.json
        - data/prepared/${preprocessor}/labels.json
        - data/prepared/${preprocessor}/preproc.joblib
        - src/train.py
      params:
        - params.yaml:lr
        - params.yaml:batch_size
        - params.yaml:epochs
      outs:
        - models/${model_class}/${file}
      metrics:
        - models/${model_class}/train_metrics.json:
            cache: false

  test:
      wdir: ../../
      cmd: python src/test.py --model-class=${model_class} --preprocessor=${preprocessor}
      deps:
        - models/${model_class}/${file}
        - src/test.py
      metrics:
        - models/${model_class}/test_metrics.json:
            cache: false

  predict:
      wdir: ../../
      cmd: python src/predict.py --model-class=${model_class}
      deps:
        - data/raw/test.csv
        - models/${model_class}/test_metrics.json
        - src/predict.py
        - models/${model_class}/${file}
      outs:
        - data/predictions/${model_class}_prediction.csv
